package CosEvents;


/**
* CosEvents/PullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEvents.idl
* Friday, December 13, 2024 11:26:10 AM WAT
*/

public interface PullSupplierOperations 
{
  void pull (org.omg.CORBA.StringHolder message);
  void disconnect_pull_supplier ();
} // interface PullSupplierOperations
