package CosEvents;


/**
* CosEvents/PushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosEvents.idl
* Friday, December 13, 2024 11:26:10 AM WAT
*/

public interface PushConsumerOperations 
{
  void push (String message);
  void disconnect_push_consumer ();
} // interface PushConsumerOperations
