package Banque;


/**
* Banque/ComptePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Friday, December 13, 2024 10:43:05 AM WAT
*/


// Interface Compte
public abstract class ComptePOA extends org.omg.PortableServer.Servant
 implements Banque.CompteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_code", new java.lang.Integer (0));
    _methods.put ("_get_solde", new java.lang.Integer (1));
    _methods.put ("depot", new java.lang.Integer (2));
    _methods.put ("retrait", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Banque/Compte/_get_code
       {
         int $result = (int)0;
         $result = this.code ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Banque/Compte/_get_solde
       {
         double $result = (double)0;
         $result = this.solde ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // Banque/Compte/depot
       {
         int montant = in.read_long ();
         this.depot (montant);
         out = $rh.createReply();
         break;
       }

       case 3:  // Banque/Compte/retrait
       {
         int montant = in.read_long ();
         this.retrait (montant);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banque/Compte:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Compte _this() 
  {
    return CompteHelper.narrow(
    super._this_object());
  }

  public Compte _this(org.omg.CORBA.ORB orb) 
  {
    return CompteHelper.narrow(
    super._this_object(orb));
  }


} // class ComptePOA
