package Banque;


/**
* Banque/Conseiller.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Friday, December 13, 2024 10:43:05 AM WAT
*/


// Interface Conseiller
public interface Conseiller extends ConseillerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conseiller
