package Banque;


/**
* Banque/ConseillerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Friday, December 13, 2024 10:43:05 AM WAT
*/


// Interface Conseiller
public abstract class ConseillerPOA extends org.omg.PortableServer.Servant
 implements Banque.ConseillerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("newCompte", new java.lang.Integer (0));
    _methods.put ("getCompte", new java.lang.Integer (1));
    _methods.put ("virement", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Banque/Conseiller/newCompte
       {
         int code = in.read_long ();
         Banque.Compte $result = null;
         $result = this.newCompte (code);
         out = $rh.createReply();
         Banque.CompteHelper.write (out, $result);
         break;
       }

       case 1:  // Banque/Conseiller/getCompte
       {
         int code = in.read_long ();
         Banque.Compte $result = null;
         $result = this.getCompte (code);
         out = $rh.createReply();
         Banque.CompteHelper.write (out, $result);
         break;
       }

       case 2:  // Banque/Conseiller/virement
       {
         Banque.Compte source = Banque.CompteHelper.read (in);
         Banque.Compte cible = Banque.CompteHelper.read (in);
         int montant = in.read_long ();
         this.virement (source, cible, montant);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banque/Conseiller:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Conseiller _this() 
  {
    return ConseillerHelper.narrow(
    super._this_object());
  }

  public Conseiller _this(org.omg.CORBA.ORB orb) 
  {
    return ConseillerHelper.narrow(
    super._this_object(orb));
  }


} // class ConseillerPOA
