package Banque;

/**
* Banque/CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, December 2, 2024 12:26:30 AM WAT
*/


// Interface Compte
public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public Banque.Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (Banque.Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Banque.CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Banque.CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Banque.CompteHelper.type ();
  }

}
