package Banque;


/**
* Banque/ConseillerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Monday, December 2, 2024 12:26:30 AM WAT
*/


// Interface Conseiller
abstract public class ConseillerHelper
{
  private static String  _id = "IDL:Banque/Conseiller:1.0";

  public static void insert (org.omg.CORBA.Any a, Banque.Conseiller that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Banque.Conseiller extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Banque.ConseillerHelper.id (), "Conseiller");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Banque.Conseiller read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConseillerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Banque.Conseiller value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Banque.Conseiller narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Banque.Conseiller)
      return (Banque.Conseiller)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Banque._ConseillerStub stub = new Banque._ConseillerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Banque.Conseiller unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Banque.Conseiller)
      return (Banque.Conseiller)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Banque._ConseillerStub stub = new Banque._ConseillerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
